anyLogicPluginsDir=/home/erik/anylogic/8.9.7/plugins
luxAnyLogicAlpxFiles.1=/home/erik/zenmo/ANYLOGIC/zero_engine/Zero_engine.alpx
luxAnyLogicAlpxFiles.2=/home/erik/zenmo/ANYLOGIC/zero_results_UI/results_UI.alpx
luxAnyLogicAlpxFiles.3=/home/erik/zenmo/ANYLOGIC/zero_Interface-Loader/Zero_Interface-Loader.alpx
